version: "3.8"
services:
  base:
    build:
      context: .
      dockerfile: ./common/images/Dockerfile.builder
    image: rps_builder:dev
  runtime:
    build:
      context: .
      dockerfile: ./common/images/Dockerfile.runtime
    image: rps_runtime:dev
  rps:
    build:
      context: ./demo
